version: '3'
services:
  sqlServer:
    container_name: 'sqlServer'
    image: mcr.microsoft.com/mssql/server
    volumes:
      - /Users/viviane_matias/Documents/Projetinhos/Desafio Backend/User_Subscription_Notifications/Docker/sqlServer
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Numsey@Password!
    ports:
      - 1401:1433

  rabbitMq:
    container_name: 'rabbitMq'
    image: rabbitmq:3-management
    volumes:
      - /Users/viviane_matias/Documents/Projetinhos/Desafio Backend/User_Subscription_Notifications/Docker/RabbitMq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit1
      - RABBITMQ_DEFAULT_PASS=Numsey@Password!
    ports:
      - 8080:15672
      - 5672:5672

networks:
  rabbitmq_go_net:
    driver: bridge
    




