version: '3'
services:
  sqlServer:
    container_name: 'sqlServer'
    image: mcr.microsoft.com/mssql/server
    volumes:
      - /Users/viviane_matias/Documents/Projetinhos/Desafio Backend/User_Subscription_Notifications/Docker/sqlServer
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Numsey@Password!
    ports:
      - 1401:1433

  rabbitMq:
    container_name: 'rabbitMq'
    image: rabbitmq:3-management
    volumes:
      - /Users/viviane_matias/Documents/Projetinhos/Desafio Backend/User_Subscription_Notifications/Docker/RabbitMq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit1
      - RABBITMQ_DEFAULT_PASS=Numsey@Password!
    ports:
      - 8080:15672
      - 5672:5672

networks:
  rabbitmq_go_net:
    driver: bridge
    

user_notification:
  container_name: 'eager_lichterman'
  image: user_notification:1.0
  volumes: 
    - /Users/viviane_matias/Documents/Projetinhos/Desafio Backend/User_Subscription_Notifications/Docker/user_notification
  restart: always
  environment:
  - ASPNETCORE_URLS:http://+:80
  - DOTNET_RUNNING_IN_CONTAINER:true
  - DOTNET_VERSION:6.0.24
  - ASPNET_VERSION:6.0.24
  ports:
    - 80
  

